services:
  backend:
    image: irinaqqq/qttech-backend:latest
    ports:
      - "8080:8000"
    environment:
      DATABASE_USER_FILE: /run/secrets/db_user
      DATABASE_PASSWORD_FILE: /run/secrets/db_password
      DATABASE_HOST_FILE: /run/secrets/db_host
    secrets:
      - db_user
      - db_password
      - db_host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      placement:
        preferences:
          - spread: node.role  # позволяет Swarm выбирать узел по ролям
        constraints:
          - node.labels.backend == true 
    networks:
      - app-net

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_host:
    external: true
networks:
  app-net:
    driver: overlay
