# Generated by Django 5.0.6 on 2024-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='graphics',
            field=models.CharField(max_length=255, null=True, verbose_name='Видеокарта'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(max_length=255, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='ports',
            field=models.TextField(null=True, verbose_name='Порты и разъемы'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(max_length=255, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=255, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(max_length=255, null=True, verbose_name='Накопители'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(null=True, verbose_name='Особенности'),
        ),
    ]
