# Generated by Django 5.0.6 on 2024-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0006_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(max_length=100, null=True, verbose_name='Особенности'),
        ),
    ]
