# Generated by Django 5.0.6 on 2024-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0009_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/product_descriptions/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/product_images/', verbose_name='Изображение'),
        ),
    ]
