# Generated by Django 5.0.6 on 2024-05-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0010_alter_productdescription_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(max_length=60, null=True, verbose_name='Особенности(кратко)'),
        ),
    ]
