# Generated by Django 5.0.6 on 2024-05-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0012_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='static/category_images/', verbose_name='Фото'),
        ),
    ]
