# Generated by Django 5.0.6 on 2024-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0015_brand_alter_processor_brand_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='series',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия'),
        ),
    ]
