# Generated by Django 5.0.6 on 2024-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0016_alter_processor_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='series',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Серия'),
        ),
    ]
