# Generated by Django 5.0.6 on 2024-05-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0017_alter_processor_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='line',
            field=models.ForeignKey(limit_choices_to={'brand': 'self.brand'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='QT_store.line', verbose_name='Линейка'),
        ),
    ]
