# Generated by Django 5.0.6 on 2024-05-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0018_alter_processor_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='line',
            field=models.ForeignKey(limit_choices_to={'brand': models.F('brand')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='QT_store.line', verbose_name='Линейка'),
        ),
        migrations.AddConstraint(
            model_name='processor',
            constraint=models.UniqueConstraint(fields=('brand', 'line', 'series'), name='unique_processor'),
        ),
    ]
