# Generated by Django 5.0.6 on 2024-05-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0019_alter_processor_line_processor_unique_processor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processor',
            name='unique_processor',
        ),
        migrations.AlterField(
            model_name='processor',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QT_store.line', verbose_name='Линейка'),
        ),
    ]
