# Generated by Django 5.0.6 on 2024-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0023_alter_ram_type_delete_ramtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR4X', 'DDR4X'), ('DDR5', 'DDR5')], max_length=10, null=True, verbose_name='Тип оперативной памяти'),
        ),
    ]
