# Generated by Django 5.0.6 on 2024-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0024_alter_ram_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='size',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='type',
        ),
        migrations.AddField(
            model_name='ram',
            name='size_and_type',
            field=models.CharField(choices=[('4GB DDR3', '4 ГБ DDR3'), ('8GB DDR3', '8 ГБ DDR3'), ('16GB DDR3', '16 ГБ DDR3'), ('32GB DDR3', '32 ГБ DDR3'), ('64GB DDR3', '64 ГБ DDR3'), ('128GB DDR3', '128 ГБ DDR3'), ('4GB DDR4', '4 ГБ DDR4'), ('8GB DDR4', '8 ГБ DDR4'), ('16GB DDR4', '16 ГБ DDR4'), ('32GB DDR4', '32 ГБ DDR4'), ('64GB DDR4', '64 ГБ DDR4'), ('128GB DDR4', '128 ГБ DDR4')], max_length=20, null=True, verbose_name='Объем и тип оперативной памяти'),
        ),
    ]
