# Generated by Django 5.0.6 on 2024-05-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0025_remove_ram_size_remove_ram_type_ram_size_and_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='size_and_type',
        ),
        migrations.AddField(
            model_name='ram',
            name='size',
            field=models.CharField(choices=[('4GB', '4 ГБ'), ('8GB', '8 ГБ'), ('16GB', '16 ГБ'), ('32GB', '32 ГБ'), ('64GB', '64 ГБ'), ('128GB', '128 ГБ')], max_length=5, null=True, verbose_name='Объем оперативной памяти'),
        ),
        migrations.AddField(
            model_name='ram',
            name='type',
            field=models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR4X', 'DDR4X'), ('DDR5', 'DDR5')], max_length=10, null=True, verbose_name='Тип оперативной памяти'),
        ),
    ]
