# Generated by Django 5.0.6 on 2024-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0026_remove_ram_size_and_type_ram_size_ram_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10, null=True, verbose_name='Тип оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.CharField(choices=[('120GB', '120 ГБ'), ('240GB', '240 ГБ'), ('480GB', '480 ГБ'), ('1TB', '1 ТБ'), ('2TB', '2 ТБ'), ('4TB', '4 ТБ')], max_length=6, null=True, verbose_name='Объем накопителя'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='type',
            field=models.CharField(choices=[('HDD', 'Hard Disk Drive (HDD)'), ('SSD', 'Solid-State Drive (SSD)'), ('NVMe', 'Non-Volatile Memory Express (NVMe)')], default='SSD', max_length=4, null=True, verbose_name='Тип накопителя'),
        ),
    ]
