# Generated by Django 5.0.6 on 2024-05-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0027_alter_ram_type_alter_storage_size_alter_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.CharField(choices=[('120GB', '120 ГБ'), ('240GB', '240 ГБ'), ('480GB', '480 ГБ'), ('1TB', '1 ТБ'), ('2TB', '2 ТБ'), ('4TB', '4 ТБ'), ('500GB', '500 ГБ'), ('1.0TB', '1.0 ТБ'), ('2.0TB', '2.0 ТБ'), ('4.0TB', '4.0 ТБ'), ('8.0TB', '8.0 ТБ'), ('16TB', '16 ТБ'), ('32TB', '32 ТБ'), ('64TB', '64 ТБ')], max_length=6, null=True, verbose_name='Объем накопителя'),
        ),
    ]
