# Generated by Django 5.0.6 on 2024-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0028_alter_storage_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип разъема')),
                ('name', models.CharField(editable=False, max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.CharField(choices=[('120GB', '120 ГБ'), ('240GB', '240 ГБ'), ('480GB', '480 ГБ'), ('500GB', '500 ГБ'), ('1TB', '1 ТБ'), ('2TB', '2 ТБ'), ('4TB', '4 ТБ'), ('8TB', '8 ТБ'), ('16TB', '16 ТБ'), ('32TB', '32 ТБ'), ('64TB', '64 ТБ')], max_length=6, null=True, verbose_name='Объем накопителя'),
        ),
    ]
