# Generated by Django 5.0.6 on 2024-05-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0029_motherboard_alter_storage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operating_humidity',
            field=models.CharField(max_length=20, null=True, verbose_name='Рабочая влажность'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_temperature',
            field=models.CharField(max_length=20, null=True, verbose_name='Температура эксплуатации'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_humidity',
            field=models.CharField(max_length=20, null=True, verbose_name='Влажность хранения'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_temperature',
            field=models.CharField(max_length=20, null=True, verbose_name='Температура хранения'),
        ),
    ]
