# Generated by Django 5.0.6 on 2024-05-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0030_product_operating_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='type',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип разъема'),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название порта'),
        ),
        migrations.AlterField(
            model_name='procbrand',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='series',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='procline',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Линейка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
