# Generated by Django 5.0.6 on 2024-05-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0031_alter_category_name_alter_motherboard_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='size_custom',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Объем накопителя (вручную)'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.CharField(choices=[('4GB', '4 ГБ'), ('8GB', '8 ГБ'), ('16GB', '16 ГБ'), ('32GB', '32 ГБ'), ('64GB', '64 ГБ'), ('128GB', '128 ГБ'), ('256GB', '256 ГБ'), ('512GB', '512 ГБ'), ('1024GB', '1 ТБ'), ('1536GB', '1,5 ТБ')], max_length=10, null=True, verbose_name='Объем оперативной памяти'),
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together={('size', 'type')},
        ),
    ]
