# Generated by Django 5.0.6 on 2024-05-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0035_screensize_alter_motherboard_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='graphics',
        ),
    ]
