# Generated by Django 5.0.6 on 2024-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0036_remove_product_graphics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discrete_graphics',
            field=models.IntegerField(blank=True, choices=[(None, 'Нет'), (2, '2GB'), (4, '4GB'), (8, '8GB'), (16, '16GB'), (24, '24GB')], null=True, verbose_name='Видеокарта дискретная'),
        ),
        migrations.AddField(
            model_name='product',
            name='keyboard_backlight',
            field=models.BooleanField(blank=True, choices=[(None, 'Нет'), (False, 'Без подсветки'), (True, 'С подсветкой')], default=None, null=True, verbose_name='Подсветка клавиатуры'),
        ),
        migrations.AddField(
            model_name='product',
            name='keyboard_type',
            field=models.CharField(blank=True, choices=[(None, 'Нет'), ('Wired', 'Проводная'), ('Wireless', 'Беспроводная')], max_length=50, null=True, verbose_name='Комплект клавиатура и мышь'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_resolution',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('Full HD', 'Full HD'), ('Quad HD', 'Quad HD'), ('4K', '4K'), ('Ultra HD+', 'Ultra HD+')], max_length=20, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_sizes',
            field=models.ManyToManyField(blank=True, to='QT_store.screensize', verbose_name='Размер экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_type',
            field=models.CharField(blank=True, choices=[(None, 'Нет'), ('IPS', 'IPS'), ('VA', 'VA'), ('TN', 'TN'), ('PLS', 'PLS'), ('LED', 'LED')], max_length=50, null=True, verbose_name='Тип экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='touch_screen',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Сенсорный экран'),
        ),
        migrations.AddField(
            model_name='product',
            name='touch_screen_touches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество касаний одновременно'),
        ),
        migrations.AddField(
            model_name='product',
            name='webcam',
            field=models.BooleanField(choices=[(None, 'Нет'), (False, 'Без встроенной вебкамеры'), (True, 'Со встроенной веб камерой')], default=None, verbose_name='Веб камера'),
        ),
    ]
