# Generated by Django 5.0.6 on 2024-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0037_product_discrete_graphics_product_keyboard_backlight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=100, verbose_name='Мощность')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_resolution',
            field=models.CharField(blank=True, choices=[(None, 'Нет'), ('HD', 'HD'), ('Full HD', 'Full HD'), ('Quad HD', 'Quad HD'), ('4K', '4K'), ('Ultra HD+', 'Ultra HD+')], max_length=20, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_supplies',
            field=models.ManyToManyField(blank=True, to='QT_store.powersupply', verbose_name='Блоки питания'),
        ),
    ]
