# Generated by Django 5.0.6 on 2024-05-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0039_product_controllers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='controllers',
        ),
    ]
