# Generated by Django 5.0.6 on 2024-05-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0042_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('Horizontal', 'Горизонтальный'), ('Vertical', 'Вертикальный')], max_length=20, null=True, verbose_name='Форм-фактор'),
        ),
    ]
