# Generated by Django 5.0.6 on 2024-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0044_alter_product_form_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='touch_screen',
            field=models.CharField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], default=False, max_length=20, verbose_name='Сенсорный экран'),
        ),
    ]
