# Generated by Django 5.0.6 on 2024-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0045_alter_product_touch_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.ManyToManyField(blank=True, null=True, to='QT_store.operatingsystem', verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.ManyToManyField(blank=True, null=True, to='QT_store.processor', verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.ManyToManyField(blank=True, null=True, to='QT_store.ram', verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(blank=True, null=True, to='QT_store.storage', verbose_name='Накопители'),
        ),
    ]
