# Generated by Django 5.0.6 on 2024-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0046_remove_product_operating_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.ManyToManyField(blank=True, to='QT_store.operatingsystem', verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.ManyToManyField(blank=True, to='QT_store.processor', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.ManyToManyField(blank=True, to='QT_store.ram', verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(blank=True, to='QT_store.storage', verbose_name='Накопители'),
        ),
    ]
