# Generated by Django 5.0.6 on 2024-06-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0049_alter_storage_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='mother',
            field=models.ManyToManyField(blank=True, to='QT_store.motherboard', verbose_name='Материнская плата'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='line',
            field=models.CharField(choices=[('Socket', 'Socket'), ('FCBGA', 'FCBGA')], default='Socket', max_length=50, verbose_name='Линейка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Особенности(кратко)'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='keyboard_backlight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_resolution',
        ),
        migrations.AlterField(
            model_name='product',
            name='touch_screen',
            field=models.CharField(blank=True, choices=[(None, 'Нет'), (True, 'Да'), (False, 'Нет')], default=None, max_length=20, null=True, verbose_name='Сенсорный экран'),
        ),
        migrations.AddField(
            model_name='product',
            name='keyboard_backlight',
            field=models.ManyToManyField(blank=True, to='QT_store.keyboardlight', verbose_name='Подсветка клавиатуры'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_resolution',
            field=models.ManyToManyField(blank=True, to='QT_store.screenresolution', verbose_name='Разрешение экрана'),
        ),
    ]
