# Generated by Django 5.0.6 on 2024-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0050_keyboardlight_screenresolution_product_mother_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formf', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='form_factor',
        ),
        migrations.AddField(
            model_name='product',
            name='formfactor',
            field=models.ManyToManyField(blank=True, to='QT_store.formfactor', verbose_name='Форм-фактор'),
        ),
    ]
