# Generated by Django 5.0.6 on 2024-06-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0052_keyboardset_remove_product_keyboard_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touches', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='discrete_graphics',
        ),
        migrations.AlterField(
            model_name='controller',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='formfactor',
            name='formf',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='keyboardlight',
            name='light',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='keyboardset',
            name='set',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='power',
            field=models.CharField(max_length=100, unique=True, verbose_name='Мощность'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='touch_screen_touches',
        ),
        migrations.AlterField(
            model_name='screenresolution',
            name='resolution',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='screensize',
            name='size',
            field=models.CharField(max_length=50, unique=True, verbose_name='Размер экрана'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='touch_screen_touches',
            field=models.ManyToManyField(blank=True, to='QT_store.touchst', verbose_name='Количество касаний одновременно'),
        ),
    ]
