# Generated by Django 5.0.6 on 2024-06-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0054_remove_product_controllers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controller',
        ),
    ]
