# Generated by Django 5.0.6 on 2024-06-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0056_controller_product_controllers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
