# Generated by Django 5.0.6 on 2024-06-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0057_alter_controller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='touch_screen_touches',
        ),
        migrations.DeleteModel(
            name='TouchST',
        ),
    ]
