# Generated by Django 5.0.6 on 2024-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0058_remove_product_touch_screen_touches_delete_touchst'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touches', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='touch_screen_touches',
            field=models.ManyToManyField(blank=True, to='QT_store.touchst', verbose_name='Количество касаний одновременно'),
        ),
    ]
