# Generated by Django 5.0.6 on 2024-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0059_touchst_product_touch_screen_touches'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_type',
        ),
        migrations.AddField(
            model_name='product',
            name='screen_type',
            field=models.ManyToManyField(blank=True, to='QT_store.screentype', verbose_name='Тип экрана'),
        ),
    ]
