# Generated by Django 5.0.6 on 2024-06-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0060_screentype_remove_product_screen_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='webcam',
        ),
        migrations.AddField(
            model_name='product',
            name='webcam',
            field=models.ManyToManyField(blank=True, to='QT_store.webcam', verbose_name='Веб камера'),
        ),
    ]
