# Generated by Django 5.0.6 on 2024-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0061_webcam_remove_product_webcam_product_webcam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': [models.OrderBy(models.F('size'), nulls_last=True), 'type']},
        ),
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.PositiveIntegerField(null=True, verbose_name='Объем накопителя(ГБ)'),
        ),
    ]
