# Generated by Django 5.0.6 on 2024-06-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0063_alter_storage_options_storage_size_tb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['-type', models.OrderBy(models.F('size'), nulls_last=True)]},
        ),
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.PositiveIntegerField(null=True, verbose_name='Объем оперативной памяти(ГБ)'),
        ),
    ]
