# Generated by Django 5.0.6 on 2024-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0064_alter_ram_options_alter_ram_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем накопителя(ГБ)'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='size_tb',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем накопителя(ТБ)'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='type',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe')], default='SSD', max_length=4, null=True, verbose_name='Тип накопителя'),
        ),
    ]
