# Generated by Django 5.0.6 on 2024-06-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0067_alter_powersupply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='power',
            field=models.PositiveIntegerField(unique=True, verbose_name='Мощность'),
        ),
    ]
