# Generated by Django 5.0.6 on 2024-06-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0068_alter_powersupply_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='product',
            name='touch_screen',
        ),
    ]
