# Generated by Django 5.0.6 on 2024-06-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0069_remove_product_ports_remove_product_touch_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
