# Generated by Django 5.0.6 on 2024-06-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0070_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_descriptions/', verbose_name='Фото'),
        ),
    ]
