# Generated by Django 5.0.6 on 2024-06-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0071_alter_productdescription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category_images/', verbose_name='Фото'),
        ),
    ]
