# Generated by Django 5.0.6 on 2024-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0072_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imageback',
            field=models.ImageField(null=True, upload_to='category_images/', verbose_name='Задний фон'),
        ),
    ]
