# Generated by Django 5.0.6 on 2024-06-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0074_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
