# Generated by Django 5.0.6 on 2024-06-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0076_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
