# Generated by Django 5.0.6 on 2024-06-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0078_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
