# Generated by Django 5.0.6 on 2024-07-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0084_registrationrequest_organisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
    ]
