# Generated by Django 5.0.6 on 2024-07-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0087_custom_organization_alter_custom_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
