# Generated by Django 5.0.6 on 2024-07-03 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0088_feedback_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QT_store.cart')),
                ('controllers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.controller')),
                ('formfactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.formfactor')),
                ('graphics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.graphics')),
                ('keyboard_backlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.keyboardlight')),
                ('keyset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.keyboardset')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.motherboard')),
                ('operating_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.operatingsystem')),
                ('power_supplies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.powersupply')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.processor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QT_store.product')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.ram')),
                ('screen_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.screenresolution')),
                ('screen_sizes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.screensize')),
                ('screen_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.screentype')),
                ('sizes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.size')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.storage')),
                ('touch_screen_touches', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.touchst')),
                ('webcam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QT_store.webcam')),
            ],
        ),
    ]
