# Generated by Django 5.0.6 on 2024-07-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0092_productitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
