# Generated by Django 5.0.6 on 2024-07-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0093_delete_productitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('processor_notes', models.TextField(blank=True, null=True)),
                ('motherboard_notes', models.TextField(blank=True, null=True)),
                ('ram_notes', models.TextField(blank=True, null=True)),
                ('storage_notes', models.TextField(blank=True, null=True)),
                ('graphics_notes', models.TextField(blank=True, null=True)),
                ('operating_system_notes', models.TextField(blank=True, null=True)),
                ('screen_size_notes', models.TextField(blank=True, null=True)),
                ('screen_type_notes', models.TextField(blank=True, null=True)),
                ('screen_resolution_notes', models.TextField(blank=True, null=True)),
                ('touch_screen_notes', models.TextField(blank=True, null=True)),
                ('form_factor_notes', models.TextField(blank=True, null=True)),
                ('webcam_notes', models.TextField(blank=True, null=True)),
                ('keyboard_set_notes', models.TextField(blank=True, null=True)),
                ('keyboard_backlight_notes', models.TextField(blank=True, null=True)),
                ('power_supply_notes', models.TextField(blank=True, null=True)),
                ('size_notes', models.TextField(blank=True, null=True)),
                ('controller_notes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='QT_store.category')),
                ('controllers', models.ManyToManyField(blank=True, to='QT_store.controller')),
                ('form_factors', models.ManyToManyField(blank=True, to='QT_store.formfactor')),
                ('graphics', models.ManyToManyField(blank=True, to='QT_store.graphics')),
                ('keyboard_backlights', models.ManyToManyField(blank=True, to='QT_store.keyboardlight')),
                ('keyboard_sets', models.ManyToManyField(blank=True, to='QT_store.keyboardset')),
                ('motherboards', models.ManyToManyField(blank=True, to='QT_store.motherboard')),
                ('operating_systems', models.ManyToManyField(blank=True, to='QT_store.operatingsystem')),
                ('power_supplies', models.ManyToManyField(blank=True, to='QT_store.powersupply')),
                ('processors', models.ManyToManyField(blank=True, to='QT_store.processor')),
                ('rams', models.ManyToManyField(blank=True, to='QT_store.ram')),
                ('screen_resolutions', models.ManyToManyField(blank=True, to='QT_store.screenresolution')),
                ('screen_sizes', models.ManyToManyField(blank=True, to='QT_store.screensize')),
                ('screen_types', models.ManyToManyField(blank=True, to='QT_store.screentype')),
                ('sizes', models.ManyToManyField(blank=True, to='QT_store.size')),
                ('storages', models.ManyToManyField(blank=True, to='QT_store.storage')),
                ('touch_screens', models.ManyToManyField(blank=True, to='QT_store.touchst')),
                ('webcams', models.ManyToManyField(blank=True, to='QT_store.webcam')),
            ],
        ),
    ]
