# Generated by Django 5.0.6 on 2024-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0096_productitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
