# Generated by Django 5.0.6 on 2024-07-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0101_alter_productitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('being_assembled', 'Собирается'), ('dispatched', 'Отправлен'), ('delivered', 'Доставлен')], default='pending_verification', max_length=20),
        ),
    ]
