# Generated by Django 5.0.6 on 2024-08-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT_store', '0102_remove_order_total_price_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='compatible_motherboards',
            field=models.ManyToManyField(blank=True, related_name='compatible_processors', to='QT_store.motherboard'),
        ),
    ]
